name: Docker Github Dev Image CI

on:
  push:
    branches: [dev]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PROJECT_NAME: "api"

    steps:
      - uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and Push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/${{ env.PROJECT_NAME }}:dev

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
