name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DB_CONNECTION: pg
      DB_HOST: localhost
      DB_PORT: 5432
      DB_DATABASE: aurora
      DB_USERNAME: root
      DB_PASSWORD: password
      DB_SSL: false
      JWT_SECRET: dummybroh

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 16.x]

    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres:12
        # Provide the password for postgres
        env:
          POSTGRES_USER: aurora
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build --if-present
      - run: npm run migrate
      - run: npm run db:seed
      - run: npm test
